#IvB May 2018
# input 1: iqtree output, arbitrary rooting, because it does not matter for treefix
# input 2: subtree from ensembl gene tree
#output 
import sys
from ete3 import Tree

repeat_tree_file = sys.argv[1] #IQ tree output to be rooted
gene_tree_file = sys.argv[2] #nhx tree, subtree generated by ensembl_api.py

input_folder = 'genetrees_nhx'
output_folder = 'denovo/treefix'
outputs_file = gene_tree_file.replace(input_folder,output_folder)
smap_file = outputs_file.replace('.nhx', '.smap')
stree_file = outputs_file.replace('.nhx', '.stree')
rooted_file = repeat_tree_file+'.rooted'

#write rooted tree
with open(repeat_tree_file, 'r') as tree_string:
	tree_string = tree_string.readline()
repeat_tree = Tree(tree_string, format=1)
topnode = repeat_tree.get_children()[0]
repeat_tree.set_outgroup(topnode)
repeat_tree.write(format=1, outfile=rooted_file)

with open(gene_tree_file,'r') as gene_tree:
	gene_tree_str = gene_tree.read()

gene_tree = Tree(gene_tree_str, format=1)

with open(smap_file,'w') as smap:
	for l in gene_tree.get_leaves():
		smap.write(l.name+'*\t'+l.name+'\n')

with open(stree_file,'w') as stree:
	stree.write(gene_tree_str.replace('[&&NHX:D=D]',''))
	
