## IvB April 2018
## Retrieve gene trees from API for selected orthologs
## Query returns subtree of only indicated taxons from a larger gene tree
## The gene trees can be seen as orthologuous groups, containing both orthologs and paralogs

#Input
## pre.orthologs_filtered_file generated by filtered_orthologs.py
# Output
## Gene tree json is saved, and to be parsed by parse_genetree.py
## pre.genes_to_genetrees_file = root+'genes_to_genetrees.json'


import requests, sys, json, os.path
from SPARQLWrapper import SPARQLWrapper, JSON
import pipeline_methods as pre
		
filtered_ogs_file = pre.orthologs_filtered_file
log_file = pre.root+'log_retrieve_genetrees.txt'

species_list = pre.get_taxon_list('', [])
species_str = '&prune_taxon='.join([str(x) for x in species_list])

ensembl_server = "http://rest.ensembl.org"
sparql=SPARQLWrapper('https://www.ebi.ac.uk/rdf/services/sparql')
sparql.setReturnFormat(JSON)

genes_to_genetrees = {}

if(pre.file_notempty(filtered_ogs_file)):
	with open(filtered_ogs_file,'r') as filtered_ogs:
		mapping = json.load(filtered_ogs)
else: 	
	print("Requires input file ",pre.orthologs_filtered_file)
	quit()	

#reset log
with open(log_file,'w') as log:
	log.write('')
	

#Retrieve gene trees for OGs
# extract subtree containing all orthologs
for gene_uri in mapping:	
	
	#json contains raw input of REST
	gene_id = gene_uri[len(pre.gene_uri_prefix):]
	orthologs_list = [gene_id]
	for orthologs in mapping[gene_uri].values():
		orthologs_list.extend([x[len(pre.gene_uri_prefix):] for x in orthologs])

	api_file_path = pre.ensembl_path+gene_id+'.json'
	
	if(pre.file_notempty(api_file_path)):
		with open(api_file_path, 'r') as gene_api_file: 
			genetree_json = json.load(gene_api_file)
	else:
		#redo
		ext = "/genetree/member/id/"+gene_id+"?sequence=protein&prune_taxon="+species_str
		r = requests.get(ensembl_server+ext, headers={  "Content-Type" : "application/json"})

		if not r.ok:
			with open(log_file, mode='ab') as log:
				log.write(r.content)
			continue
		
		genetree_json = r.json() 
		with open(api_file_path, 'w') as gene_api_file: 
			gene_api_file.write(json.dumps(genetree_json))
		
	genetree_id = genetree_json['id']
	og_id = genetree_id+'_'+gene_id
	genes_to_genetrees[gene_id]=genetree_id
	print(og_id)	

with open(pre.genes_to_genetrees_file, 'w') as output_g2g:		
	output_g2g.write(json.dumps(genes_to_genetrees))				 

		
	
